### ISSUE TITLE
Print version shows login data

### ISSUE THREAD

**Issue by durandalrt** [LouisOuellet/dokuwiki_template_writr#3]
### Description

When trying to print, I get the User Name, icon and buttons on the page.

### Steps to reproduce

1. Open page on browser. Tried Chrome and Edge
2. Print
3. User Name, User Icon and Buttons are displayed on the top on the page, twice.

### Versions

* [Writr] (2024-11-04)
* [DokuWiki] Release 2024-02-06b "Kaos"
* [Plugins] 
* [PHP] 7.4.12
* [Browser] Chrome and Edge

**Comment by LouisOuellet** [comment]
hmmm.. Been working on the responsive design of the template. Changing the scope of some css may have cause this issue. I'll look into it

**Comment by LouisOuellet** [comment]
Just submitted a commit covering this issue.

**Comment by durandalrt** [comment]
Just tested your changes, and now only shows data once, as seen in the attached screenshot. 
![Captura de pantalla 2024-11-05 104009](https://github.com/user-attachments/assets/b805ccdc-d31a-4f5f-bd8b-c9c1cdabf02c)

**Comment by LouisOuellet** [comment]
Just pushed 2024-11-05b with a fix for this :D

**Comment by durandalrt** [comment]
Thanks a lot, works perfectly!
