### ISSUE TITLE
Conflict with diagrams.net plugin

### ISSUE THREAD

**Issue by durandalrt** [LouisOuellet/dokuwiki_template_writr#4]
### Description

Using the diagrams.net plugin, when you open de diagrams editor, sidebar buttons still visible.

### Steps to reproduce

1. Open page on browser. Tried Chrome and Edge
2. Edit diagram using Diagrams NET plugin (https://www.dokuwiki.org/plugin:diagramsnet)
3. Sidebar buttons still visible
![ss](https://github.com/user-attachments/assets/db2a247b-b13a-4d6f-ba96-9d598c29fe91)

### Versions

* [Writr] (2024-11-04)
* [DokuWiki] Release 2024-02-06b "Kaos"
* [Plugins] 
* [PHP] 7.4.12
* [Browser] Chrome and Edge

**Comment by LouisOuellet** [comment]
I see the issue xD. I'll check it out

**Comment by LouisOuellet** [comment]
Also what is the plugin attached to the O button, below the move button? Just curious if I can add a proper icon to it.

**Comment by LouisOuellet** [comment]
hmmm. Not sure this plugin works under PHP 8.2 and support for PHP 7.4 has reach end of life since November 28, 2022. I am unable to find the editor anywhere. Adding a diagram using the button only adds the markdown.

So far, I can't replicate. Though I'll try with other similar plugin like draw.io and diagrams

**Comment by LouisOuellet** [comment]
Just tested [draw.io](https://www.dokuwiki.org/plugin:drawio) and [diagrams](https://www.dokuwiki.org/plugin:diagrams). Both work as expected on the template.

Have you tried upgrading to php 8.2?

**Comment by LouisOuellet** [comment]
You can find a full list of the extensions I test and have themed here : https://laswitchtech.com/en/blog/projects/writr/documentation/01/01/index

**Comment by LouisOuellet** [comment]
Just submitted an [issue](https://github.com/todag/dokuwiki-plugin-diagramsnet/issues/1) on the plugin's source.

**Comment by durandalrt** [comment]
Thanks for your support. I just tried the new revision you submitted and now it works fine.

I'll look into PHP version, though. Thanks for the remark.
